import { test, expect, signIn, navigateAdmin } from './fixtures.mjs'

test('public default view persists on the Hub while visitor switching stays local', async ({ page, hub }) => {
  const id = await hub.node('Public view node', true)
  await hub.node('Private node', false)
  await hub.request('/api/settings', { method:'PUT', body:{ public_page:'on' } })
  await signIn(page)
  await navigateAdmin(page, '设置')
  const setting = page.getByRole('combobox', { name:'公开页默认视图', exact:true })
  await expect(setting).toContainText('卡片')
  await setting.click()
  await page.getByRole('option', { name:'列表', exact:true }).click()
  await page.getByRole('button', { name:'保存站点设置', exact:true }).click()
  await expect.poll(async () => (await hub.request('/api/settings')).public_default_view).toBe('list')
  await page.request.post('/api/auth/logout')
  await page.goto('/')
  await expect(page.getByRole('table', { name:'公开节点列表' })).toBeVisible()
  await expect(page.getByText('Private node', { exact:true })).toHaveCount(0)
  await page.getByRole('link', { name:'Public view node', exact:true }).click()
  await expect(page).toHaveURL(new RegExp(`/node/${id}$`))
  await page.getByRole('button', { name:'返回', exact:true }).click()
  await expect(page.getByRole('button', { name:'列表', exact:true })).toHaveAttribute('aria-pressed','true')
  await page.getByRole('button', { name:'卡片', exact:true }).click()
  await expect(page.locator('.public-node-card')).toHaveCount(1)
  await page.reload()
  await expect(page.getByRole('table', { name:'公开节点列表' })).toBeVisible()
  expect((await page.request.put('/api/settings',{data:{public_default_view:'cards'}})).status()).toBe(401)
})

test('admin management list has copyable stable identities and no duplicate installation action', async ({ page, context, hub }) => {
  const id = await hub.node('Managed node', true)
  await signIn(page)
  await expect(page.getByRole('group', { name:'节点视图' })).toHaveCount(0)
  await expect(page.getByRole('button', { name:'重新接入', exact:true })).toHaveCount(0)
  await expect(page.locator('.admin-version')).toContainText('未上报')
  await context.grantPermissions(['clipboard-read','clipboard-write'])
  const copy = page.getByRole('button',{name:'复制 Managed node 接入标识',exact:true})
  await copy.focus()
  await page.keyboard.press('Space')
  await expect.poll(() => page.evaluate(() => navigator.clipboard.readText())).toBe(`node-${id}`)
  for (const width of [320,692,1101,1326]) {
    await page.setViewportSize({width,height:831})
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    expect(await page.locator('.admin-node-table td').evaluateAll(cells=>cells.every(td=>td.scrollWidth<=td.clientWidth+1))).toBe(true)
    if (width > 1100) {
      const tops = await page.locator('.admin-node-table tbody tr').evaluate(row => [...row.children].map(td => td.querySelector('.admin-primary,.text-button,.address-line,.copy-value,button').getBoundingClientRect().top))
      expect(new Set(tops).size).toBe(1)
    }
  }
  await page.getByRole('button',{name:'编辑菜单 Managed node',exact:true}).click()
  await expect(page.getByRole('button',{name:'安装 Agent',exact:true})).toHaveCount(1)
  await page.getByRole('button',{name:'关闭',exact:true}).click()
  await hub.request('/api/ping-tasks',{method:'POST',body:{name:'Checkbox check',target:'service.example.invalid:443',interval:60,nodes:[id]}})
  await navigateAdmin(page,'监测')
  await page.getByRole('button',{name:'编辑监测',exact:true}).click()
  const checkbox = page.getByRole('checkbox',{name:'Managed node',exact:true})
  await expect(checkbox).toBeChecked()
  const marks = await checkbox.evaluate(el=>({before:getComputedStyle(el,'::before').content,after:getComputedStyle(el,'::after').content}))
  expect(marks.before).not.toBe('none')
  expect(marks.after).toBe('none')
  await page.getByRole('button',{name:'关闭',exact:true}).click()
  for(let n=0;n<8;n++) await hub.node(`Scroll node ${n}`,true)
  await navigateAdmin(page,'节点')
  await expect(page.locator('.admin-node-table tbody tr')).toHaveCount(9)
  await page.setViewportSize({width:390,height:831})
  const menu = page.getByRole('button',{name:'打开导航',exact:true})
  // Measure after focusing: locator.click may scroll the trigger before dispatching input.
  await menu.focus()
  const before = await page.locator('main').boundingBox()
  await menu.press('Enter')
  expect(await page.locator('main').boundingBox()).toEqual(before)
  const drawer = await page.getByRole('dialog').boundingBox()
  expect(drawer.x).toBe(0);expect(drawer.y).toBe(0);expect(drawer.height).toBe(831)
  await page.getByRole('dialog').press('Escape')
  await expect(menu).toBeFocused()
})
