// Builds the two generated data files the v15 prototype loads.
//
//   node designs/romi-next/revision-v15/tools/build-assets.mjs <lucide-icons-dir> <land-110m.json>
//
// <lucide-icons-dir>  the `icons/` folder of lucide-static@1.34.0 (ISC), or a folder
//                     holding the subset named in ICONS below
// <land-110m.json>    world-atlas@2.0.2 land-110m.json (ISC; derived from Natural
//                     Earth 1:110m land, public domain)
//
// Writes icons.js and land.js next to this folder. Design-time only: nothing here
// runs in the prototype or in a hub.
import { readFileSync, writeFileSync } from "node:fs"
import { join, resolve } from "node:path"

const OUT = resolve(import.meta.dirname, "..")
const [iconDir, landFile] = process.argv.slice(2)
if (!iconDir || !landFile) {
  console.error("usage: build-assets.mjs <lucide-icons-dir> <land-110m.json>")
  process.exit(64)
}

const ICONS = `search x plus check copy chevron-down chevron-right chevron-left chevron-up arrow-left arrow-up
arrow-down arrow-up-right sun moon log-out settings bell database shield radar server layout-grid list ellipsis
pencil trash-2 download upload refresh-cw key-round square-terminal eye eye-off globe clock wifi-off triangle-alert
info circle-check lock menu command calendar wallet external-link rotate-ccw wrench history monitor smartphone laptop
loader-circle keyboard tag power gauge file-archive map-pin activity network cpu memory-stick hard-drive send webhook
user circle-x circle-alert zap timer sliders-horizontal arrow-down-up ticket copy-check link-2 play pause
sunrise sunset languages`
  .split(/\s+/)
  .filter(Boolean)

const icons = {}
for (const name of ICONS) {
  const svg = readFileSync(join(iconDir, `${name}.svg`), "utf8")
  const body = svg
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/^[\s\S]*?<svg[^>]*>/, "")
    .replace(/<\/svg>[\s\S]*$/, "")
    .replace(/\s*\n\s*/g, "")
    .replace(/\s+\/>/g, "/>")
  icons[name] = body
}
writeFileSync(
  join(OUT, "icons.js"),
  `// Generated by tools/build-assets.mjs from lucide-static@1.34.0 (ISC, see ../vendor/lucide-LICENSE.txt).\n` +
    `window.romiIcons=${JSON.stringify(icons)};\n`,
)

// ---- land mask ------------------------------------------------------------
// TopoJSON arcs are delta-encoded in a quantised grid; decode them to lon/lat.
const topo = JSON.parse(readFileSync(landFile, "utf8"))
const { scale, translate } = topo.transform
const arcs = topo.arcs.map((arc) => {
  let x = 0
  let y = 0
  return arc.map(([dx, dy]) => {
    x += dx
    y += dy
    return [x * scale[0] + translate[0], y * scale[1] + translate[1]]
  })
})
const ring = (indices) => {
  const points = []
  for (const i of indices) {
    const arc = i < 0 ? arcs[~i].slice().reverse() : arcs[i]
    points.push(...(points.length ? arc.slice(1) : arc))
  }
  return points
}
const polygons = []
const collect = (geometry) => {
  if (geometry.type === "GeometryCollection") geometry.geometries.forEach(collect)
  else if (geometry.type === "Polygon") polygons.push(geometry.arcs.map(ring))
  else if (geometry.type === "MultiPolygon") geometry.arcs.forEach((p) => polygons.push(p.map(ring)))
}
collect(topo.objects.land)

const inside = (lon, lat, points) => {
  let hit = false
  for (let i = 0, j = points.length - 1; i < points.length; j = i++) {
    const [xi, yi] = points[i]
    const [xj, yj] = points[j]
    if (yi > lat !== yj > lat && lon < ((xj - xi) * (lat - yi)) / (yj - yi) + xi) hit = !hit
  }
  return hit
}
const boxes = polygons.map((rings) => {
  const xs = rings[0].map((p) => p[0])
  const ys = rings[0].map((p) => p[1])
  return [Math.min(...xs), Math.min(...ys), Math.max(...xs), Math.max(...ys)]
})
const land = (lon, lat) =>
  polygons.some((rings, k) => {
    const [x0, y0, x1, y1] = boxes[k]
    if (lon < x0 || lon > x1 || lat < y0 || lat > y1) return false
    return inside(lon, lat, rings[0]) && !rings.slice(1).some((hole) => inside(lon, lat, hole))
  })

// Half-degree cells, sampled at their centres, north to south. Each row is
// run-length encoded as alternating sea/land counts in base 36.
const STEP = 0.5
const COLS = 360 / STEP
const ROWS = 180 / STEP
const rows = []
let landCells = 0
for (let r = 0; r < ROWS; r++) {
  const lat = 90 - STEP / 2 - r * STEP
  const runs = []
  let current = false
  let run = 0
  for (let c = 0; c < COLS; c++) {
    const lon = -180 + STEP / 2 + c * STEP
    const value = land(lon, lat)
    if (value) landCells++
    if (value === current) run++
    else {
      runs.push(run)
      current = value
      run = 1
    }
  }
  runs.push(run)
  rows.push(runs.map((n) => n.toString(36)).join("."))
}
writeFileSync(
  join(OUT, "land.js"),
  `// Generated by tools/build-assets.mjs from world-atlas@2.0.2 land-110m (ISC), itself\n` +
    `// Natural Earth 1:110m land (public domain). ${STEP}° cells, rows north to south,\n` +
    `// alternating sea/land run lengths in base 36.\n` +
    `window.romiLand={step:${STEP},rows:${JSON.stringify(rows.join("|"))}};\n`,
)
console.log(`icons ${Object.keys(icons).length}, land cells ${landCells} of ${COLS * ROWS}`)
